/** Repository barrel — typed data access for every table. */
export * from './projects';
export * from './properties';
export * from './parties';
export * from './categories';
export * from './transactions';
export * from './investors';
export * from './capital';
export * from './milestones';
export * from './documents';
export * from './sales';
export * from './udhaar';
export * from './acquisition';
export * from './reports';
export * from './investments';
export * from './exit';
export * from './settlement';
export * from './analytics';
export * from './settings';
